"""Added LoanOffer table

Revision ID: 3c91bbd8cf3b
Revises: 7e41cbd95d65
Create Date: 2026-02-26 10:02:27.012914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c91bbd8cf3b'
down_revision = '7e41cbd95d65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('logo', sa.String(length=255), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('processing_fee', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loan_offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank_id', sa.Integer(), nullable=False),
    sa.Column('interest_rate', sa.Float(), nullable=False),
    sa.Column('max_amount', sa.Integer(), nullable=True),
    sa.Column('tenure_months', sa.Integer(), nullable=True),
    sa.Column('approval_time', sa.String(length=100), nullable=True),
    sa.Column('affiliate_link', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['bank_id'], ['banks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('loan_offers')
    op.drop_table('banks')
    # ### end Alembic commands ###
